# --- Configuraci√≥n Global ---
global:
  postgresql:
    auth:
      postgresPassword: "supersecretpassword"
      username: "neuralbank"
      password: "neuralbank123!"
      database: "neuralbank"

# --- Backend ---
backend:
  image:
    repository: quay.io/maximilianopizarro/neuralbank-backend
    tag: "latest"
    pullPolicy: Always
  service:
    port: 8080
  replicaCount: 1

# --- Frontend ---
frontend:
  image:
    repository: quay.io/maximilianopizarro/neuralbank-front 
    tag: "pkce"
    pullPolicy: Always
  service:
    port: 8080
  replicaCount: 1


# --- Keycloak Configuration ---
keycloak:
  issuerUrl: 'https://rhbk.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/realms/neuralbank'
  clientId: 'neuralbank-frontend'
  clientSecret: 'hg6hlG50pjVtiNpzzPpgSQxCJVPVwNLu'
  authorizationEndpoint: 'https://rhbk.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/realms/neuralbank/protocol/openid-connect/auth'
  redirectUri: 'https://neuralbank.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/auth/callback'
  tokenEndpoint: 'https://rhbk.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/realms/neuralbank/protocol/openid-connect/token'
  postLogoutRedirectUri: 'https://neuralbank.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com'

# --- API Configuration ---
api:
  baseUrl: '/api'